# Generates a Docker container with an installed GenTen built with clang-sycl
# compiler and CUDA parallelism.
#
# This is intended to be run from the top-level genten source tree

# Base image -- assumes an image with the sycl compiler is already created
ARG BASE=sycl:base
FROM $BASE
MAINTAINER Eric Phipps <etphipp@sandia.gov>

# Change to bash so we have, e.g., -o pipefail
SHELL ["/bin/bash", "-c"]

# Install GenTen dependencies
RUN \
  apt-get update --yes && \
  apt-get install --yes \
    cmake \
    libblas-dev \
    liblapack-dev \
    libboost-iostreams-dev \
    gfortran \
    && \
  rm -rf /var/lib/apt/lists/*

# Add genten src
RUN mkdir -p /src
COPY . /src/genten

ARG ARCH=BDW
ARG GPU=VOLTA70

# Setup environment
ENV \
  GENTEN_ARCH=${ARCH} \
  GENTEN_GPU=${GPU} \
  GENTEN_SRC_PATH=/src/genten \
  GENTEN_INSTALL_PATH=/usr

# Build and install genten
RUN \
  set -o pipefail && \
  mkdir -p /build/genten  && \
  cd /build/genten && \
  ${GENTEN_SRC_PATH}/scripts/gitlab_sycl_cuda/do_configure.sh 2>&1 | tee cmake_output.txt && \
  make -j8 install 2>&1 | tee make_output.txt
