FROM ruyman/dpcpp_cuda_examples as base

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    cmake \
    libblas-dev \
    liblapack-dev \
    libthrust-dev \
    ccache \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
