FROM rocm/dev-ubuntu-20.04 as base

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    cmake \
    libblas-dev \
    liblapack-dev \
    rocblas-dev \
    rocsolver-dev \
    rocthrust-dev \
    ccache \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
