#!/bin/bash

KOKKOS=../../kokkos
INSTALL=`pwd`/../../install/opt_intel_openmp

${KOKKOS}/generate_makefile.bash \
  --kokkos-path=${KOKKOS} \
  --prefix=${INSTALL} \
  --with-openmp \
  --arch=KNL \
  --compiler=icpc \
  --with-options=aggressive_vectorization
